# =============================================================================
# Monochrome
# =============================================================================

foreground              #e5e5e5
background              #111111

selection_foreground    #111111
selection_background    #e5e5e5

cursor                  #ffffff
cursor_text_color       #111111

url_color               #bdbdbd

active_border_color     #ffffff
inactive_border_color   #333333

active_tab_background   #ffffff
active_tab_foreground   #111111

inactive_tab_background #111111
inactive_tab_foreground #666666

tab_bar_background      #111111

# ANSI

color0  #1a1a1a
color8  #555555

color1  #808080
color9  #bdbdbd

color2  #808080
color10 #bdbdbd

color3  #808080
color11 #bdbdbd

color4  #808080
color12 #bdbdbd

color5  #808080
color13 #bdbdbd

color6  #808080
color14 #bdbdbd

color7  #e5e5e5
color15 #ffffff
