add_newline = false

format = "$username$hostname $directory$character"

[username]
show_always = true
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
trim_at = "."
style = "green bold"
format = "[@$hostname]($style)"

[directory]
truncation_length = 1
truncate_to_repo = false
style = "blue bold"
format = "[$path]($style)"

[character]
success_symbol = "\\$ "
error_symbol = "\\$ "
vicmd_symbol = "\\$ "
