# =============================================================================
# Cyberdream (Pure Black Workspace)
# =============================================================================

# Status bar
set -g status-style                 "bg=#16181a,fg=#ffffff"
set -g status-left-length           40
set -g status-right-length          80

set -g status-left                  "#[bg=#ffbd5e,fg=#000000,bold] #S #[bg=#16181a,fg=#ffbd5e]"
set -g status-right                 "#[fg=#3c4048]  #[fg=#ffffff]%H:%M  #[fg=#3c4048]|#[fg=#ffffff]  %d %b  #[fg=#3c4048]|  #[fg=#bd5eff]#H "

# Window list
setw -g window-status-format         " #[fg=#7b8496]#I#[fg=#3c4048]:#[fg=#a0a8cd]#W#{?window_zoomed_flag, [Z],} "

setw -g window-status-current-format " #[fg=#bd5eff,bold]#I#[fg=#3c4048]:#[fg=#ffffff,bold]#W#{?window_zoomed_flag, [Z],} "

setw -g window-status-current-style  "bg=#3c4048"
setw -g window-status-activity-style "fg=#f1ff5e"
setw -g window-status-separator      ""

# Panes
set -g pane-border-style            "fg=#3c4048"
set -g pane-active-border-style     "fg=#bd5eff"

set -g display-panes-colour         "#3c4048"
set -g display-panes-active-colour  "#bd5eff"

# Messages
set -g message-style                "bg=#16181a,fg=#ffffff"
set -g message-command-style        "bg=#16181a,fg=#ffbd5e"
set -g mode-style                   "bg=#3c4048,fg=#ffffff"

# Clock
set -g clock-mode-colour            "#bd5eff"
