[mgr]
show_hidden = false
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "size"
show_symlink = true
scrolloff = 5

[preview]
wrap = "yes"
tab_size = 4
max_width = 1600
max_height = 2000

[opener]

open = [
    { run = 'xdg-open %s1', orphan = true }
]

[open]

rules = [
    { mime = "text/*", use = "open" },
    { mime = "application/pdf", use = "open" },
    { mime = "image/*", use = "open" },
    { mime = "video/*", use = "open" },
    { mime = "audio/*", use = "open" },

    { mime = "application/zip", use = "open" },
    { mime = "application/x-tar", use = "open" },
    { mime = "application/gzip", use = "open" },
    { mime = "application/x-bzip2", use = "open" },
    { mime = "application/x-xz", use = "open" },
    { mime = "application/x-7z-compressed", use = "open" },
    { mime = "application/x-rar", use = "open" },

    { mime = "inode/directory", use = "open" },
]
