general.import = [
  "~/.config/alacritty/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
padding = { x = 2, y = 0 }
dynamic_padding = false
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = false

[window.dimensions]
columns = 120
lines = 34

[scrolling]
history = 10000
multiplier = 5

[font]
size = 12

[font.normal]
family = "IosevkaTerm NFM"
style = "Medium"

[font.bold]
family = "IosevkaTerm NFM"
style = "Bold"

[font.italic]
family = "IosevkaTerm NFM"
style = "Medium Italic"

[font.bold_italic]
family = "IosevkaTerm NFM"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]

# [terminal.shell]
# program = "/usr/bin/zellij"

[keyboard]

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
action = "ResetFontSize"

# [[keyboard.bindings]]
# key = "F5"
# mods = "Control|Shift"
# action = "ReloadConfiguration"
